### ISSUE TITLE
Group by Tag shows nothing in Flat View

### ISSUE THREAD

**Issue by geekley** [Gruntfuggly/todo-tree#498]
Toggling group by tag works in tree view and tags-only view, but not in flat view.
Instead of showing the items grouped, it just shows nothing.

### Versions
Todo Tree: 0.0.211
VSCodium: 1.55.2 Linux snap

**Comment by Gruntfuggly** [comment]
The was broken in version 0.0.196! 

Should now be working in the latest version (0.0.212).

**Comment by geekley** [comment]
I tested 212, but it's still not right...
In both flat and tree view, when I enable grouping, it has "Scan mode: workspace and open files", but it shows few results (only 1 file is showing results?). When I right click and switch scan mode to something else, then back, it shows more results. If I disable grouping then re-enable it, it goes back to showing less results.

Only tags view seems to be doing grouping right...

**Comment by Gruntfuggly** [comment]
Please could you attach some screen shots to show what is happening?

If possible could you also post your settings and some examples of the TODOs which show the problem?

**Comment by geekley** [comment]
Well, I tried to make a minimal reproducible example (to send you the code), but I can't reproduce it reliably. For example, if I reload the editor, the problem might go away, but when creating new TODOs, it might happen again. What I mean is that I couldn't figure out a step-by-step that is guaranteed to reproduce it (and I can't share my private project, but I'm sure if you have lots of files and TODOs on a project, and keep toggling the group button on mode "workspace and open files" you'll eventually catch it).

I can, however, share some screenshots for that minimal example where I've been able to catch it (they aren't necessarily in order).

Here, you can see that there's a total of 5 items. Note the FIXME "asdasdasd" from the file "Assembly.cs":
![image](https://user-images.githubusercontent.com/38332912/116308485-ec2c2a00-a77d-11eb-9819-cf9505e4935b.png)

If I toggle groups, it only shows 2 items, and FIXME is an empty group:
![image](https://user-images.githubusercontent.com/38332912/116308172-95265500-a77d-11eb-950d-edfc97cfd584.png)

On this file, it's not showing the ones from the other files (Program.cs and csproj):
![image](https://user-images.githubusercontent.com/38332912/116308716-3b725a80-a77e-11eb-8de1-c0862c397b7e.png)

By clicking refresh, it seems the problem is solved?
![image](https://user-images.githubusercontent.com/38332912/116309269-f1d63f80-a77e-11eb-98c7-2cd1283629cd.png)

The settings I used here:
```jsonc
  "editor.fontSize": 11.5, // gutter icons don't scale properly
  "todo-tree.highlights.enabled": true,
  "todo-tree.filtering.excludeGlobs": [
    "**/vendor/**",
    "**/node_modules/**",
    "**/dist/**",
    "**/bower_components/**",
    "**/build/**",
    "**/.vscode/**",
    "**/.github/**",
    "**/_output/**",
    "**/*.min.*",
    "**/*.map"
  ],
  "todo-tree.general.statusBar": "tags",
  "todo-tree.tree.labelFormat": "${afterOrBefore}",
  "todo-tree.tree.tooltipFormat": "${filepath}:${line}\n${tag} ${after}",
  "todo-tree.tree.hideIconsWhenGroupedByTag": true,
  "todo-tree.tree.flat": true,
  "todo-tree.tree.expanded": true,
  "todo-tree.tree.showScanModeButton": false,
  "todo-tree.general.showIconsInsteadOfTagsInStatusBar": true,
  "todo-tree.general.statusBarClickBehaviour": "reveal",
  "todo-tree.highlights.useColourScheme": true,
  // "todo-tree.general.tags": [
  //   "FIXME",
  //   "TODO",
  //   "TODO?",
  //   "TEST",
  // ],
  "todo-tree.highlights.backgroundColourScheme": [
    // "#c46f0d",
    "editorWarning.foreground",
    // "#CCC",
    "editorHint.foreground",
    // "#888",
    "editorHint.foreground",
    // "#c05b91",
    "editorInfo.foreground",
  ],
  "todo-tree.highlights.foregroundColourScheme": [
    "editor.background",
  ],
  "todo-tree.highlights.defaultHighlight": {
    "opacity": 0,
    "rulerOpacity": 0.25,
    "fontWeight": "bold",
    // "textDecoration": "underline",
    "borderRadius": "3px",
    "gutterIcon": true, // doesn't scale properly with font size / line height
  },
  "todo-tree.highlights.customHighlight": {
    "FIXME": {
      "icon": "$(bug)",
      "rulerOpacity": 0.75,
      // "textDecoration": "double underline",
      "gutterIcon": true, // off-scale
    },
    "TODO": {
      "icon": "$(pin)",
    },
    "TODO?": {
      "icon": "$(question)",
    },
    "TEST": {
      "icon": "$(beaker)",
    },
```

By the way (unrelated) maybe it's better if the default regex has a word boundary after tags? Like `...($TAGS)\b|...`. This way it wouldn't match words partially, like, for example FIX in `//FIXED`.

**Comment by Gruntfuggly** [comment]
I tried adding the word boundary to the default regex once before, but it caused problems for existing users. As a rule I no longer update the default regex as it causes too many issues.

What would be most useful would be if you could grab the output from the debug log (enable `todo-tree.general.debug`) when it does something wrong. There should never be a node which can expand but has no contents. When that happens, could you check if there are any errors in the developer tools console?

Lastly, are you using the default regex?

**Comment by geekley** [comment]
OK, I'll see if I can catch it again later with log enabled.
Yes, I'm using default regex.

**Comment by Gruntfuggly** [comment]
I think it's to do with the `todo-tree.tree.labelFormat` setting - if I use yours I get odd behaviour, with the default it's fine. I'll try and work out whats going on - can you try the default and see what happens?

**Comment by Gruntfuggly** [comment]
I've made a small tweak - could you test it for me please?
[todo-tree-0.0.214-beta.vsix.zip](https://github.com/Gruntfuggly/todo-tree/files/6397995/todo-tree-0.0.214-beta.vsix.zip)

**Comment by Gruntfuggly** [comment]
OK - think I've finally tracked it down. Should be fixed in the next release.

**Comment by Gruntfuggly** [comment]
I've finally got round to uploading a new version which should fix this. Please let me know if it works as expected.
